package Norris::Web::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Norris::Web::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:norris',
        user => 'root',
        password => '',
        AutoCommit => q{1},
    }
);

=head1 NAME

Norris::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Norris::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Norris::Web::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

Adam Taylor

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
